### ISSUE TITLE
[Feat] Adding "DevOps Roadmap" page 

### ISSUE THREAD

**Issue by Hamza1821** [mdazfar2/HelpOps-Hub#1415]
### Description

This project currently lacks a dedicated section that provides insights into **DevOps** and the pathway to becoming a **DevOps Engineer**. To bridge this gap, I plan to create a new page from scratch that will feature key sections, such as **"What is DevOps?"** and a **comprehensive roadmap** outlining the essential technologies and skills needed to embark on the journey of becoming a successful **DevOps Engineer**.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/mdazfar2/HelpOps-Hub/blob/main/CONTRIBUTING.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by mdazfar2** [comment]
@Hamza1821 As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.
